### ISSUE TITLE
如何批量生产pdf双语

### ISSUE THREAD

**Issue by xyh2132** [jesselau76/ebook-GPT-translator#2]
若每次执行换一次命令,想按顺序每次批量转,命令如何改

**Comment by xyh2132** [comment]
python3 text_translation.py example.pdf
请问执行本命令后,转化出来的是json文件,非PDF,那里出的问题?

**Comment by jesselau76** [comment]
json文件是进度文件。最终结果是epub和txt文件。pdf不太好做保持原有格式，所以我没有输出结果为pdf文件。

**Comment by jesselau76** [comment]
openai的api似乎有限制。最好一次转一个文件
