### ISSUE TITLE
请问无法找到命令地址是怎么回事？

### ISSUE THREAD

**Issue by moehippo** [jesselau76/ebook-GPT-translator#30]
![屏幕截图 2023-04-17 192408](https://user-images.githubusercontent.com/66999928/232470664-9afe65ea-0989-4e20-8644-cf2187bf4926.png)
我是新手，请问找不到命令是怎么回事？

**Comment by jesselau76** [comment]
只需要运行python3 text_translation.py example.pdf
就可

**Comment by moehippo** [comment]
非常感谢。我用python3 命令无法实现，但是用python命令实现了。我还遇到一个编码错误的问题，我修改了脚本添加了读取utf-8编码。非常感谢你！

发自我的 iPhone

在 2023年4月18日，09:14，jesselau76 ***@***.***> 写道：

﻿

只需要运行python3 text_translation.py example.pdf
就可
